import { MoonIcon, SunIcon } from '@chakra-ui/icons';
import {
  Box,
  Flex,
  IconButton,
  useColorMode,
  useColorModeValue,
  HStack
} from '@chakra-ui/react';
import Head from 'next/head';
import { ReactNode } from 'react';
import {
  EFFECTIVE_WIDTHS,
  GITHUB_LINK,
  LINKEDIN_LINK,
  TWITTER_LINK
} from '../../lib/constants';
import { ExternalLink } from '../Links';

export function Layout({ children }: { children: ReactNode }) {
  const { colorMode, toggleColorMode } = useColorMode();
  const bg = useColorModeValue('white', 'gray.800');

  return (
    <div>
      <Head>
        <title>How long</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        as="header"
        boxShadow="sm"
        display="flex"
        flexDirection="row"
        justifyContent="center"
        position="fixed"
        top={0}
        width="100%"
        background={bg}
        zIndex={1}
      >
        <Flex
          flexDirection="row"
          justifyContent="flex-end"
          alignItems="center"
          px={3}
          py={2}
          width={EFFECTIVE_WIDTHS}
        >
          <IconButton
            aria-label={`Toggle ${
              colorMode === 'light' ? 'dark' : 'light'
            } mode`}
            variant="ghost"
            onClick={toggleColorMode}
            borderRadius="50%"
            colorScheme="teal"
          >
            {colorMode === 'light' ? <MoonIcon /> : <SunIcon />}
          </IconButton>
        </Flex>
      </Box>

      <Box
        height="calc(100vh - 56px)"
        mt="56px"
        display="flex"
        flexDirection="column"
        alignItems="center"
      >
        <Box
          width={EFFECTIVE_WIDTHS}
          display="flex"
          flexDirection="column"
          height="100%"
        >
          <Box flex="1 1 0%" p={4}>
            {children}
          </Box>

          <Box as="footer" flex="0 0 0%" p={4}>
            <Box fontWeight={700} mb={2} textAlign="center">
              Copyright &copy; 2021 Try Ajitiono.
            </Box>

            <HStack
              as="ul"
              listStyleType="none"
              display="flex"
              flexDirection="row"
              justifyContent="center"
            >
              <Box as="li">
                <ExternalLink href={TWITTER_LINK}>Twitter</ExternalLink>
              </Box>
              <Box as="li">
                <ExternalLink href={GITHUB_LINK}>GitHub</ExternalLink>
              </Box>
              <Box as="li">
                <ExternalLink href={LINKEDIN_LINK}>LinkedIn</ExternalLink>
              </Box>
            </HStack>
          </Box>
        </Box>
      </Box>
    </div>
  );
}
