import { MoonIcon, SunIcon } from '@chakra-ui/icons';
import {
  Box,
  Flex,
  IconButton,
  useColorMode,
  useColorModeValue
} from '@chakra-ui/react';
import Head from 'next/head';
import Image from 'next/image';
import { ReactNode } from 'react';
import { EFFECTIVE_WIDTHS } from '../../lib/constants';

export function Layout({ children }: { children: ReactNode }) {
  const { colorMode, toggleColorMode } = useColorMode();
  const bg = useColorModeValue('white', 'gray.800');

  return (
    <div>
      <Head>
        <title>How long</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        as="header"
        boxShadow="sm"
        display="flex"
        flexDirection="row"
        justifyContent="center"
        position="fixed"
        top={0}
        width="100%"
        background={bg}
        zIndex={1}
      >
        <Flex
          flexDirection="row"
          justifyContent="flex-end"
          alignItems="center"
          px={3}
          py={2}
          width={EFFECTIVE_WIDTHS}
        >
          <IconButton
            aria-label={`Toggle ${colorMode === 'light' ? 'Dark' : 'Light'}`}
            variant="ghost"
            onClick={toggleColorMode}
            borderRadius="50%"
          >
            {colorMode === 'light' ? <MoonIcon /> : <SunIcon />}
          </IconButton>
        </Flex>
      </Box>

      <Box height="calc(100vh - 56px)" mt="56px">
        {children}

        <footer>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </Box>
    </div>
  );
}
